[ECA-512] Ajustes plugin Magento 2
PicPay/magento2 pull request #20
Opened 2022-02-24 13:48 UTC by moacirjun

2022-03-03 18:42 UTC, andrebparpaiola requested changes

2022-03-03 18:42 UTC, andrebparpaiola commented on Gateway/Response/TxnIdHandler.php
> +            $this->logger->error('picpay payment error', $context);
Talvez colocar um nome mais específico ajudaria a localizarmos depois, o que acha?

2022-03-03 19:00 UTC, moacirjun commented on Gateway/Response/TxnIdHandler.php
> +            $this->logger->error('picpay payment error', $context);
Que tal `picpay creating order error`?
e59561c7f4a9f7ed7699a0434ce863e6add2968e

2022-03-03 19:11 UTC, andrebparpaiola commented on Gateway/Response/TxnIdHandler.php
> +            $this->logger->error('picpay payment error', $context);
Boa, eu gostei. Ficou mais indicativo do que de fato faz.

2022-03-03 19:12 UTC, andrebparpaiola approved these changes

2022-03-04 12:16 UTC, hugobandeira approved these changes

2022-03-04 12:26 UTC, merged